'`Os métodos de strings.`'
print('hello'.capitalize())
print('MaRiO'.casefold())
print('centro'.center(20,'-'))
print('abcabcabcabc'.count('ab'))
print('Elon Musk'.encode("utf-8","strict"))
print('apple'.endswith(('e','a')))
print('texto\ttexto\ttexto'.expandtabs(20))
print('abcdefghi'.find('def'))
print('{n1} {n2} {n3}'.format(n1=10,n2=30,n3=20))
print('({x},{y})'.format_map({'x':10,'y':5}))
print('abcdefghi'.index('fgh'))
print('abcde1234'.isalnum())
print('abcde'.isalpha())
print('ab¢d£§'.isascii())
print('12345'.isdecimal())
print('¹²³'.isdigit())
print('abcdefghi'.isnumeric())
print('test'.isidentifier())
print('Abc'.islower())
print('12345\n'.isprintable())
print('    '.isspace())
print('The Video'.istitle())
print('ABCDEF'.isupper())
print('--'.join(['a','b','c']))
print('texto'.ljust(20,'_'))
print('ABCDEF'.lower())
print('_texto_'.lstrip('_'))
print('texto'.maketrans('t','´'))
print('texto'.translate(''.maketrans('t','´')))
print('a+b=c'.partition('='))
print('texto'.removeprefix('tex'))
print('texto'.removesuffix('to'))
print('texto'.replace('tex','___'))
print('A algo A b'.rfind('A'))
print('A algo B A B'.rindex('B'))
print('texto'.rjust(20,'-'))
print('A=B=C'.rpartition('='))
print('A=B=C=D=E'.rsplit('='))
print('A=B=C=D=E'.split('=',maxsplit=2))
print('My name is ____'.rstrip('_'))
print('texto\nqualquer\n'.splitlines(keepends=True))
print('ABC'.startswith('A'))
print('Luigi has pasta'.strip('Luigi '))
print('Luigi has pasta'.swapcase())
print('um texto'.title())
print('um texto'.upper())
print('texto'.zfill(20))